package com.porpoise.codefornode.ui;

import java.io.File;
import java.util.List;

import javax.swing.ButtonGroup;

import com.google.common.base.CharMatcher;
import com.google.common.base.Joiner;
import com.google.common.collect.Lists;
import com.porpoise.codefornode.ui.Swing.OpenMode;

/**
 * 
 * @author aaron.pritzlaff
 */
public class CodeForNodePanel extends javax.swing.JPanel {

    public static interface Controller {
        /**
         * @param xmlFile
         * @param destDir
         * @param pckg
         */
        String generate(File xmlFile, File destDir, String pckg, TargetLanguage language);

    }

    private final Controller controller;

    /** Creates new form CodeForNodePanel */
    public CodeForNodePanel(final Controller c) {
        this.controller = c;
        initComponents();
    }

    /**
	 * 
	 */
    void initFromPrefs() {
        Swing.initFromPrefs(this.textFieldDest, "");
        Swing.initFromPrefs(this.textFieldXml, "");
        Swing.initFromPrefs(this.textFieldPackage, "");
        final String language = Swing.getUserPreference("language", TargetLanguage.Scala.name());

        final boolean useScala = TargetLanguage.valueOf(language) == TargetLanguage.Scala;
        this.radioButtonScala.setSelected(useScala);
        this.radioButtonJava.setSelected(!useScala);

        final ButtonGroup languageGroup = new ButtonGroup();
        languageGroup.add(this.radioButtonScala);
        languageGroup.add(this.radioButtonJava);

    }

    public static void main(final String[] args) {
        final Controller c = new Controller() {
            @Override
            public String generate(final File xmlFile, final File destDir, final String pckg, final TargetLanguage language) {
                return String.format("file=%s%ndest=%s%npckg=%s%nlang=%s", xmlFile.getName(), destDir.getName(), pckg, language);
            }
        };
        showCodeForNode(c);
    }

    /**
     * @param c
     */
    public static void showCodeForNode(final Controller c) {
        Swing.setDefaultTheme();
        final CodeForNodePanel p = new CodeForNodePanel(c);
        Swing.show("CodeForNode", p);
        p.initFromPrefs();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        buttonGroupLanguage = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaOutput = new javax.swing.JTextArea();
        textFieldDest = new javax.swing.JTextField();
        buttonFind = new javax.swing.JButton();
        textFieldPackage = new javax.swing.JTextField();
        buttonGenerate = new javax.swing.JButton();
        radioButtonScala = new javax.swing.JRadioButton();
        radioButtonJava = new javax.swing.JRadioButton();
        panelInputXml = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaInputXml = new javax.swing.JTextArea();
        textFieldXml = new javax.swing.JTextField();
        buttonFindXml = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setBackground(java.awt.SystemColor.window);

        jLabel1.setText("Destination Directory:");

        jLabel3.setText("Package Name:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Output"));

        textAreaOutput.setColumns(20);
        textAreaOutput.setRows(5);
        jScrollPane1.setViewportView(textAreaOutput);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
        );

        textFieldDest.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textFieldDestKeyReleased(evt);
            }
        });

        buttonFind.setText("Find");
        buttonFind.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonFindMouseClicked(evt);
            }
        });
        buttonFind.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buttonFindKeyReleased(evt);
            }
        });

        textFieldPackage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textFieldPackageKeyReleased(evt);
            }
        });

        buttonGenerate.setText("Generate");
        buttonGenerate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonGenerateMouseClicked(evt);
            }
        });
        buttonGenerate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buttonGenerateKeyReleased(evt);
            }
        });

        radioButtonScala.setMnemonic('S');
        radioButtonScala.setText("Scala");
        radioButtonScala.setToolTipText("Generate Scala Code");

        radioButtonJava.setMnemonic('J');
        radioButtonJava.setText("Java");
        radioButtonJava.setToolTipText("Generate Java Code");

        panelInputXml.setBorder(javax.swing.BorderFactory.createTitledBorder("Input XML"));

        textAreaInputXml.setColumns(20);
        textAreaInputXml.setRows(5);
        jScrollPane2.setViewportView(textAreaInputXml);

        textFieldXml.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textFieldXmlKeyReleased(evt);
            }
        });

        buttonFindXml.setText("Find");
        buttonFindXml.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonFindXmlMouseClicked(evt);
            }
        });
        buttonFindXml.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buttonFindXmlKeyReleased(evt);
            }
        });

        jLabel4.setText("Input Xml:");

        javax.swing.GroupLayout panelInputXmlLayout = new javax.swing.GroupLayout(panelInputXml);
        panelInputXml.setLayout(panelInputXmlLayout);
        panelInputXmlLayout.setHorizontalGroup(
            panelInputXmlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInputXmlLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldXml, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonFindXml)
                .addGap(4, 4, 4))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
        );
        panelInputXmlLayout.setVerticalGroup(
            panelInputXmlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputXmlLayout.createSequentialGroup()
                .addGroup(panelInputXmlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldXml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonFindXml)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE))
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/porpoiseSmall.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelInputXml, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(radioButtonScala)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButtonJava)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 426, Short.MAX_VALUE)
                        .addComponent(buttonGenerate))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textFieldDest, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                                .addGap(6, 6, 6)
                                .addComponent(buttonFind))
                            .addComponent(textFieldPackage, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)))
                    .addComponent(jLabel5))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelInputXml, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textFieldDest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonFind))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textFieldPackage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonGenerate)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radioButtonScala)
                        .addComponent(radioButtonJava)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonFindXmlMouseClicked(final java.awt.event.MouseEvent evt) {// GEN-FIRST:event_buttonFindXmlMouseClicked
        Swing.find(this, this.textFieldXml, OpenMode.FILES_ONLY);
    }// GEN-LAST:event_buttonFindXmlMouseClicked

    private void buttonFindXmlKeyReleased(final java.awt.event.KeyEvent evt) {// GEN-FIRST:event_buttonFindXmlKeyReleased
        if (Swing.isEnter(evt)) {
            Swing.find(this, this.textFieldXml, OpenMode.FILES_ONLY);
        }
    }// GEN-LAST:event_buttonFindXmlKeyReleased

    /**
	 * 
	 */
    private void doGenerate() {
        final File xmlFile = new File(this.textFieldXml.getText());
        final File destDir = new File(this.textFieldDest.getText());
        final String pckg = this.textFieldPackage.getText();

        final List<String> errors = Lists.newArrayList();
        if (!CharMatcher.JAVA_LETTER.or(CharMatcher.is('.')).matchesAllOf(pckg)) {
            errors.add(String.format("Invalid java package '%s'", pckg));
        }
        if (!xmlFile.exists()) {
            errors.add(String.format("Couldn't find input file '%s'", xmlFile.getPath()));
        }
        if (destDir.exists()) {
            if (!destDir.isDirectory()) {
                errors.add(String.format("'%s' is not a directory", destDir.getPath()));
            }
        } else if (!destDir.mkdirs()) {
            errors.add(String.format("Couldn't create directory '%s'", destDir.getPath()));
        }

        if (errors.isEmpty()) {
            final String results = this.controller.generate(xmlFile, destDir, pckg, getTargetLanguage());
            savePrefs();
            this.textAreaOutput.setText(results);
        } else {
            final String errorMsg = Joiner.on(String.format(",%n")).join(errors);
            Swing.showError(this, errorMsg);
        }
    }

    /**
	 * 
	 */
    public void savePrefs() {
        Swing.savePrefs(this.textFieldPackage);
        Swing.savePrefs(this.textFieldXml);
        Swing.savePrefs(this.textFieldDest);
        Swing.savePrefs("language", getTargetLanguage().name());
    }

    public TargetLanguage getTargetLanguage() {
        if (this.radioButtonScala.isSelected()) {
            return TargetLanguage.Scala;
        }
        return TargetLanguage.Java;
    }

    private void buttonFindKeyReleased(final java.awt.event.KeyEvent evt) {// GEN-FIRST:event_buttonFindKeyReleased
                                                                           // TODO add your handling code here:
    }// GEN-LAST:event_buttonFindKeyReleased

    private void textFieldPackageKeyReleased(final java.awt.event.KeyEvent evt) {// GEN-FIRST:event_textFieldPackageKeyReleased
        if (Swing.isEnter(evt)) {
            doGenerate();
        }
    }// GEN-LAST:event_textFieldPackageKeyReleased

    private void textFieldDestKeyReleased(final java.awt.event.KeyEvent evt) {// GEN-FIRST:event_textFieldDestKeyReleased
        if (Swing.isEnter(evt)) {
            Swing.find(this, this.textFieldDest, OpenMode.DIRECTORIES_ONLY);
        }
    }// GEN-LAST:event_textFieldDestKeyReleased

    private void textFieldXmlKeyReleased(final java.awt.event.KeyEvent evt) {// GEN-FIRST:event_textFieldXmlKeyReleased
        if (Swing.isEnter(evt)) {
            Swing.find(this, this.textFieldXml, OpenMode.FILES_ONLY);
        }
    }// GEN-LAST:event_textFieldXmlKeyReleased

    private void buttonFindMouseClicked(final java.awt.event.MouseEvent evt) {// GEN-FIRST:event_buttonFindMouseClicked
        Swing.find(this, this.textFieldDest, OpenMode.DIRECTORIES_ONLY);
    }// GEN-LAST:event_buttonFindMouseClicked

    private void buttonGenerateMouseClicked(final java.awt.event.MouseEvent evt) {// GEN-FIRST:event_buttonGenerateMouseClicked
        doGenerate();
    }// GEN-LAST:event_buttonGenerateMouseClicked

    private void buttonGenerateKeyReleased(final java.awt.event.KeyEvent evt) {// GEN-FIRST:event_buttonGenerateKeyReleased
        if (Swing.isEnter(evt)) {
            doGenerate();
        }
    }// GEN-LAST:event_buttonGenerateKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonFind;
    private javax.swing.JButton buttonFindXml;
    private javax.swing.JButton buttonGenerate;
    private javax.swing.ButtonGroup buttonGroupLanguage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelInputXml;
    private javax.swing.JRadioButton radioButtonJava;
    private javax.swing.JRadioButton radioButtonScala;
    private javax.swing.JTextArea textAreaInputXml;
    private javax.swing.JTextArea textAreaOutput;
    private javax.swing.JTextField textFieldDest;
    private javax.swing.JTextField textFieldPackage;
    private javax.swing.JTextField textFieldXml;
    // End of variables declaration//GEN-END:variables

}
